path_gender_identifier: /mnt/default/zcodetasks/code/mogabr-codes/proj_git/gender_rewriting_WANLP/save_folder_male_female_male_female-camelbertmsa/dev_167000
path_speaker_listener_identifier: /mnt/default/zcodetasks/code/mogabr-codes/proj_git/gender_rewriting_WANLP/save_folder_speaker_listener_speaker_listener_camelbertmsa/dev_133000
data_path: /mnt/default/zcodetasks/code/mogabr-codes/proj_data/Arabic-parallel-gender-corpus-v-2.1/data
m2_edits_path: /mnt/default/zcodetasks/code/mogabr-codes/proj_data/m2_edits
model_name: CAMeL-Lab/bert-base-arabic-camelbert-msa
model_name_s2s: UBC-NLP/AraT5-msa-base
path_to_s2s_generation: /mnt/default/zcodetasks/code/mogabr-codes/proj_git_2/gender_rewriting_WANLP/save_folder_FF_arat5msa_seq2seq_augmented/dev_40000/generated_dev_data.txt
path_to_s2s_generation_MF: /mnt/default/zcodetasks/code/mogabr-codes/proj_git_2/gender_rewriting_WANLP/save_folder_MF_arat5msa_seq2seq_augmented/dev_60000/generated_dev_data.txt
path_to_s2s_generation_FM: /mnt/default/zcodetasks/code/mogabr-codes/proj_git_2/gender_rewriting_WANLP/save_folder_FM_arat5msa_seq2seq_augmented/dev_57000/generated_dev_data.txt
path_to_s2s_generation_MM: /mnt/default/zcodetasks/code/mogabr-codes/proj_git_2/gender_rewriting_WANLP/save_folder_MM_arat5msa_seq2seq_augmented/dev_57000/generated_dev_data.txt
exp_name: full_pipeline_eval_no_dict_seq2seqwaugment
output_save_location: /mnt/default/zcodetasks/code/mogabr-codes/proj_git/gender_rewriting_WANLP_results/save_folder_blindddd
speak_listen_mode: MM
remove_dict: True
max_length: 128
batch_size: 16
use_augmented: false
no_epochs: 10
eval_every: 1000
learning_rate: 0.00001
device: cuda