exp_name: speaker_listener_marbertv2
data_path: /mnt/default/zcodetasks/code/mogabr-codes/proj_data/Arabic-parallel-gender-corpus-v-2.1/data
model_saves_path: ./save_folder_speaker_listener
model_name: UBC-NLP/MARBERTv2 # UBC-NLP/AraT5-msa-base
speak_listen_mode: MM
max_length: 128
batch_size: 16
no_epochs: 10
eval_every: 1000
learning_rate: 0.00001
device: cuda
calc_score_at_eval: true
